apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordertracking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordertracking
  template:
    metadata:
      labels:
        app: ordertracking
    spec:
      containers:
      - name: ordertracking
        image: ordertracking-service:latest # Replace with the correct Docker image name and tag
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ordertracking-service
spec:
  type: NodePort
  selector:
    app: ordertracking
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
