apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderconfirmation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderconfirmation
  template:
    metadata:
      labels:
        app: orderconfirmation
    spec:
      containers:
      - name: orderconfirmation
        image: orderconfirmation-service:latest # Replace with the correct Docker image name and tag
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: orderconfirmation-service
spec:
  type: NodePort
  selector:
    app: orderconfirmation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
