apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsdelivered-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smsdelivered
  template:
    metadata:
      labels:
        app: smsdelivered
    spec:
      containers:
      - name: smsdelivered
        image: smsdelivered-service:latest # Replace with the correct Docker image name and tag
        ports:
        - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: smsdelivered-service
spec:
  type: NodePort
  selector:
    app: smsdelivered
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004
