apiVersion: apps/v1
kind: Deployment
metadata:
  name: weborder-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weborder
  template:
    metadata:
      labels:
        app: weborder
    spec:
      containers:
      - name: weborder
        image: weborder-service:latest # Replace with the correct Docker image name and tag
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weborder-service
spec:
  type: NodePort
  selector:
    app: weborder
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
