apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryconfirmation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryconfirmation
  template:
    metadata:
      labels:
        app: deliveryconfirmation
    spec:
      containers:
      - name: deliveryconfirmation
        image: deliveryconfirmation-service:latest # Replace with the correct Docker image name and tag
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: deliveryconfirmation-service
spec:
  type: NodePort
  selector:
    app: deliveryconfirmation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
